### ISSUE TITLE
Create migration and seed files

### ISSUE THREAD

**Issue by slim-hmidi** [sqorn/sqorn#10]
Hi, 
Thank you for creating this great library. I want to suggest the creation of  migration and seed files like `knex`.
What do you think about adding some postgresql functions like `create index` and `drop table` and the other functions?

**Comment by eejdoowad** [comment]
I plan to eventually so that users don't have to find another library just for migrations. Until then, you can use existing migration tools, like [knex's migrator](https://knexjs.org/#Migrations) and [node-pg-migrate](https://github.com/salsita/node-pg-migrate).

**Comment by airhorns** [comment]
Closing this as out of scope for now.
