### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by ald890** [sqorn/sqorn#56]
Any database driver for mysql?

**Comment by eejdoowad** [comment]
Not dead. Just busy on my end. I’m planning to get back to it.

**Comment by tuananh** [comment]
wow, last commit was 23 days ago and you're asking if this project is dead?

**Comment by oreqizer** [comment]
Soo still alive?

**Comment by ald890** [comment]
@tuananh  ...and now last commit in December

**Comment by esatterwhite** [comment]
😞
