### ISSUE TITLE
Safety of query composability

### ISSUE THREAD

**Issue by javiertury** [sqorn/sqorn#57]
Hi,

I reviewed this code a while ago and I have some security concerns. I am interested in how sqorn deals with nested tagged templates. As far as I understand it uses [this helper function](https://github.com/sqorn/sqorn/blob/e943c40e273221cf449295d960765f46564fd517/packages/sqorn-lib-util/src/tagged_template.js) to differentiate parameters to be binded from nested tagged templates.

```
const isTaggedTemplate = ([strings]) => Array.isArray(strings) && strings.raw
```

Let say this is how my API finds users.

```
sq.where`id IN ${ctx.body.users}`
```

Now suppose that a malicious user submits a value for ctx.body.users that has the same structure as a tagged template, for instance `ctx.body.users = [['(1234) ; DROP ALL TABLES; --', ''], 'dummy']`. Is there any mechanism in sqorn that prevents interpreting this value as a tagged template?

**Comment by eejdoowad** [comment]
In short, this is not a vulnerability. Let me clarify:

`isTaggedTemplate` is used to identify whether a function call is a tagged template call. It examines the arguments of a function call you, the developer, writes, and uses that information to determine whether you used its tagged template overload. It is similar to how you might write an overloaded function that accepts either a number or a string, differentiating the two cases with a `typeof var` expression.

`isTaggedTemplate` is NEVER used to interpret tagged template arguments (or regular function call arguments). Rather, all tagged template arguments are parameterized, except for arguments of type function with property `build` of type function. In this situation, the argument's build function is called to build its portion of the query.

**Comment by javiertury** [comment]
So using the JSON or XML interfaces, users cannot create an array instance with a named property `raw`. They can create only a regular array, or a object with the `raw` property, not both. Thank you for this explanation.

Regarding the problem of using a regular function call, I think it would be the callers fault, not sqorn. So I will close this issue.
